/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ocl_rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <pthread.h>
#include <arpa/inet.h>

#include <CL/cl.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

#define MCAST_ADDR "239.192.1.100"
#define MAX_PEERS 10

typedef struct thread_opts {
    int sock;
    uint16_t tcp_port;
    uint16_t udp_port;
    struct timeval udp_time;
} thread_opts_t;


static int
get_cl_info(char *info)
{
    int idx = 0;
    char buf[1024];
    size_t size;
    size_t items[4];

    cl_platform_id platform;
    cl_device_id device;
    cl_uint num_devices;
    cl_uint max_dim;

    clGetPlatformIDs(1, &platform, NULL);
    clGetPlatformInfo(platform, CL_PLATFORM_VENDOR, sizeof(buf), buf, NULL);

    if (strncmp("Intel", buf, 5) == 0) {
        clGetDeviceIDs(platform, CL_DEVICE_TYPE_CPU, 1, &device, NULL);
    }
    else {
        clGetDeviceIDs(platform, CL_DEVICE_TYPE_CPU, 1, &device, &num_devices);
    }

    clGetDeviceInfo(device, CL_DEVICE_NAME, sizeof(buf), buf, &size);
    idx += sprintf(info + idx, "dev_name %s\n", buf);

    clGetDeviceInfo(device, CL_DEVICE_MAX_COMPUTE_UNITS, sizeof(max_dim), 
        &max_dim, NULL);
    idx += sprintf(info + idx, "max_comp_units %d\n", max_dim);

    clGetDeviceInfo(device, CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS, sizeof(max_dim), 
        &max_dim, NULL);
    idx += sprintf(info + idx, "max_work_item %d\n", max_dim);

    clGetDeviceInfo(device, CL_DEVICE_MAX_WORK_GROUP_SIZE, sizeof(max_dim), 
        &max_dim, NULL);
    idx += sprintf(info + idx, "max_group_size %d\n", max_dim);

    clGetDeviceInfo(device, CL_DEVICE_MAX_CLOCK_FREQUENCY, sizeof(max_dim), 
        &max_dim, NULL);
    idx += sprintf(info + idx, "max_freq %d\n", max_dim);

    return idx;
}

static int
create_mcast_sock(const char *udp_addr, const uint16_t port)
{
    int sock, optval = 1, optlen = sizeof(optval), result;
    struct sockaddr_in addr;
    socklen_t addr_len = sizeof(addr);
    struct ip_mreq mreq;

    if ((sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)) < 0) {
        fprintf(stderr, "socket failed\n");
        return -1;
    }

    optval = 1;
    result = setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &optval, optlen);
    result = setsockopt(sock, IPPROTO_IP, IP_MULTICAST_TTL, &optval, optlen);

    optval = 1;
    result = setsockopt(sock, IPPROTO_IP, IP_MULTICAST_LOOP, &optval, optlen);

    mreq.imr_multiaddr.s_addr = inet_addr(MCAST_ADDR),
    mreq.imr_interface.s_addr = INADDR_ANY;
    
    result = setsockopt(sock, IPPROTO_IP, IP_ADD_MEMBERSHIP, &mreq, sizeof(mreq));
    if (result < 0) {
        fprintf(stderr, "setsockopt membership failed\n");
        close(sock);
        return -1;
    }

    memset(&addr, 0, addr_len);
    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    addr.sin_addr.s_addr = INADDR_ANY;

    if (bind(sock, (struct sockaddr*) &addr, addr_len) < 0) {
        fprintf(stderr, "bind failed\n");
        close(sock);
        return -1;
    }
    return sock;
}

static int
mcast_listen(thread_opts_t *opts)
{
    char buf[1024];
    char info[1024];
    struct sockaddr_in addr;
    ssize_t rcount;
    socklen_t addr_len = sizeof(addr);
    int in_size;
    int sock = opts->sock;

    in_size = get_cl_info(info) + 1;

    while (1) {
        rcount = recvfrom(sock, buf, sizeof(buf), 0, (struct sockaddr*) &addr,
                          &addr_len);

        if (rcount <= 0) {
            fprintf(stderr, "recvfrom failed\n");
            close(sock);
            return -1;
        }

        printf("recv >> %s\n", buf);

        if (strncmp(buf, "hello", 5) == 0) {
            rcount = sendto(sock, info, in_size, 0, (struct sockaddr *) &addr,
                addr_len);
        }
    }
    return 0;
}

static void *
start_mcast_thread(void *data)
{
    thread_opts_t *opts = (thread_opts_t *) data;
    mcast_listen(opts);
    pthread_exit(NULL);
}

static void *
handle_client(void *arg)
{
    int sock = (int) arg;
    char buf[1024];
    ssize_t nread;
    int total = 0;

    while (1) {
        if ((nread = recv(sock, buf, sizeof(buf), 0)) < 1) {
            fprintf(stderr, "recv failed\n");
            break;
        }
        total += nread;
    }

    printf("total %d\n", total);
    close(sock);
    pthread_exit(NULL);
}

static int
tcp_listen(const char *ip, const uint16_t port)
{
    int sock, cli_sock, opt;
    struct sockaddr_in addr;
    socklen_t addr_len = sizeof(addr);
    pthread_t thread_id;

    if ((sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)) < 0) {
        fprintf(stderr, "socket failed\n");
        return -1;
    }

    if (setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt)) < 0) {
        fprintf(stderr, "setsockopt failed\n");
        return -1;
    }

    memset(&addr, 0, addr_len);
    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    addr.sin_addr.s_addr = INADDR_ANY;

    if (bind(sock, (struct sockaddr *) &addr, addr_len) < 0) {
        fprintf(stderr, "bind failed\n");
        close(sock);
        return -1;
    }

    if (listen(sock, MAX_PEERS) < 0) {
        fprintf(stderr, "listen failed\n");
        close(sock);
        return -1;
    }

    while (1) {
        cli_sock = accept(sock, (struct sockaddr *) &addr, &addr_len);
        if (cli_sock < 0) {
            fprintf(stderr, "accept failed\n");
            break;
        }

        if (pthread_create(&thread_id, NULL, handle_client, 
            (void *) cli_sock) != 0) {
            fprintf(stderr, "pthread_create failed\n");
            close(cli_sock);
            break;
        }

        pthread_detach(thread_id);
    }
    return 0;
}

static void *
start_tcp_thread(void *data)
{
    thread_opts_t *opts = (thread_opts_t *) data;
    tcp_listen(NULL, opts->tcp_port);
    pthread_exit(NULL);
}


void
ocl_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		plat_id_t get_plat_id_1_arg;
		plat_info_t get_plat_info_1_arg;
		get_devs_t get_devs_id_1_arg;
		create_ctx_t create_ctx_1_arg;
		create_cqueue_t create_cqueue_1_arg;
		create_prog_ws_t create_prog_ws_1_arg;
		build_prog_t build_prog_1_arg;
		create_kern_t create_kern_1_arg;
		create_buf_t create_buf_1_arg;
		set_kern_arg_t set_kern_arg_1_arg;
		enq_ndr_kern_t enq_ndr_kern_1_arg;
		finish_t finish_1_arg;
		enq_map_buf_t enq_map_buf_1_arg;
		enq_read_buf_t enq_read_buf_1_arg;
		enq_write_buf_t enq_write_buf_1_arg;
		release_mem_t release_mem_1_arg;
		release_prog_t release_prog_1_arg;
		release_kern_t release_kern_1_arg;
		release_cqueue_t release_cqueue_1_arg;
		release_ctx_t release_ctx_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GET_PLAT_ID:
		_xdr_argument = (xdrproc_t) xdr_plat_id_t;
		_xdr_result = (xdrproc_t) xdr_plat_id_t;
		local = (char *(*)(char *, struct svc_req *)) get_plat_id_1_svc;
		break;

	case GET_PLAT_INFO:
		_xdr_argument = (xdrproc_t) xdr_plat_info_t;
		_xdr_result = (xdrproc_t) xdr_plat_info_t;
		local = (char *(*)(char *, struct svc_req *)) get_plat_info_1_svc;
		break;

	case GET_DEVS_ID:
		_xdr_argument = (xdrproc_t) xdr_get_devs_t;
		_xdr_result = (xdrproc_t) xdr_get_devs_t;
		local = (char *(*)(char *, struct svc_req *)) get_devs_id_1_svc;
		break;

	case CREATE_CTX:
		_xdr_argument = (xdrproc_t) xdr_create_ctx_t;
		_xdr_result = (xdrproc_t) xdr_create_ctx_t;
		local = (char *(*)(char *, struct svc_req *)) create_ctx_1_svc;
		break;

	case CREATE_CQUEUE:
		_xdr_argument = (xdrproc_t) xdr_create_cqueue_t;
		_xdr_result = (xdrproc_t) xdr_create_cqueue_t;
		local = (char *(*)(char *, struct svc_req *)) create_cqueue_1_svc;
		break;

	case CREATE_PROG_WS:
		_xdr_argument = (xdrproc_t) xdr_create_prog_ws_t;
		_xdr_result = (xdrproc_t) xdr_create_prog_ws_t;
		local = (char *(*)(char *, struct svc_req *)) create_prog_ws_1_svc;
		break;

	case BUILD_PROG:
		_xdr_argument = (xdrproc_t) xdr_build_prog_t;
		_xdr_result = (xdrproc_t) xdr_build_prog_t;
		local = (char *(*)(char *, struct svc_req *)) build_prog_1_svc;
		break;

	case CREATE_KERN:
		_xdr_argument = (xdrproc_t) xdr_create_kern_t;
		_xdr_result = (xdrproc_t) xdr_create_kern_t;
		local = (char *(*)(char *, struct svc_req *)) create_kern_1_svc;
		break;

	case CREATE_BUF:
		_xdr_argument = (xdrproc_t) xdr_create_buf_t;
		_xdr_result = (xdrproc_t) xdr_create_buf_t;
		local = (char *(*)(char *, struct svc_req *)) create_buf_1_svc;
		break;

	case SET_KERN_ARG:
		_xdr_argument = (xdrproc_t) xdr_set_kern_arg_t;
		_xdr_result = (xdrproc_t) xdr_set_kern_arg_t;
		local = (char *(*)(char *, struct svc_req *)) set_kern_arg_1_svc;
		break;

	case ENQ_NDR_KERN:
		_xdr_argument = (xdrproc_t) xdr_enq_ndr_kern_t;
		_xdr_result = (xdrproc_t) xdr_enq_ndr_kern_t;
		local = (char *(*)(char *, struct svc_req *)) enq_ndr_kern_1_svc;
		break;

	case FINISH:
		_xdr_argument = (xdrproc_t) xdr_finish_t;
		_xdr_result = (xdrproc_t) xdr_finish_t;
		local = (char *(*)(char *, struct svc_req *)) finish_1_svc;
		break;

	case ENQ_MAP_BUF:
		_xdr_argument = (xdrproc_t) xdr_enq_map_buf_t;
		_xdr_result = (xdrproc_t) xdr_enq_map_buf_t;
		local = (char *(*)(char *, struct svc_req *)) enq_map_buf_1_svc;
		break;

	case ENQ_READ_BUF:
		_xdr_argument = (xdrproc_t) xdr_enq_read_buf_t;
		_xdr_result = (xdrproc_t) xdr_enq_read_buf_t;
		local = (char *(*)(char *, struct svc_req *)) enq_read_buf_1_svc;
		break;

	case ENQ_WRITE_BUF:
		_xdr_argument = (xdrproc_t) xdr_enq_write_buf_t;
		_xdr_result = (xdrproc_t) xdr_enq_write_buf_t;
		local = (char *(*)(char *, struct svc_req *)) enq_write_buf_1_svc;
		break;

	case RELEASE_MEM:
		_xdr_argument = (xdrproc_t) xdr_release_mem_t;
		_xdr_result = (xdrproc_t) xdr_release_mem_t;
		local = (char *(*)(char *, struct svc_req *)) release_mem_1_svc;
		break;

	case RELEASE_PROG:
		_xdr_argument = (xdrproc_t) xdr_release_prog_t;
		_xdr_result = (xdrproc_t) xdr_release_prog_t;
		local = (char *(*)(char *, struct svc_req *)) release_prog_1_svc;
		break;

	case RELEASE_KERN:
		_xdr_argument = (xdrproc_t) xdr_release_kern_t;
		_xdr_result = (xdrproc_t) xdr_release_kern_t;
		local = (char *(*)(char *, struct svc_req *)) release_kern_1_svc;
		break;

	case RELEASE_CQUEUE:
		_xdr_argument = (xdrproc_t) xdr_release_cqueue_t;
		_xdr_result = (xdrproc_t) xdr_release_cqueue_t;
		local = (char *(*)(char *, struct svc_req *)) release_cqueue_1_svc;
		break;

	case RELEASE_CTX:
		_xdr_argument = (xdrproc_t) xdr_release_ctx_t;
		_xdr_result = (xdrproc_t) xdr_release_ctx_t;
		local = (char *(*)(char *, struct svc_req *)) release_ctx_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}


int
main (int argc, char **argv)
{


    thread_opts_t opts;
    opts.udp_port = 51234;
    opts.tcp_port = 51234;
    opts.sock = create_mcast_sock(NULL, opts.udp_port);

    pthread_t mcast_thread, tcp_thread;
    pthread_create(&mcast_thread, NULL, start_mcast_thread, &opts);
    pthread_create(&tcp_thread, NULL, start_tcp_thread, &opts);


	register SVCXPRT *transp;

	pmap_unset (OCL_PROG, OCL_VERS);

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, OCL_PROG, OCL_VERS, ocl_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (OCL_PROG, OCL_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
