/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ocl_rpc.h"

bool_t
xdr_plat_id_t (XDR *xdrs, plat_id_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->platform))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_platforms))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_plat_info_t (XDR *xdrs, plat_info_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->platform))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->param_name))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->param_value_size))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->param_value.param_value_val, (u_int *) &objp->param_value.param_value_len, ~0))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->param_value_size_ret))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_devs_t (XDR *xdrs, get_devs_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->platform))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->device_type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_entries))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->devices))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->num_devices))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_create_ctx_t (XDR *xdrs, create_ctx_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->properties))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_devices))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->devices))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->callback))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->user_data))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->errorcode_ret))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->context))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_create_cqueue_t (XDR *xdrs, create_cqueue_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->context))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->device))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->properties))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->errorcode_ret))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->queue))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_create_prog_ws_t (XDR *xdrs, create_prog_ws_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->context))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->strings, ~0))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->lengths))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->errorcode_ret))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->prog))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_build_prog_t (XDR *xdrs, build_prog_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->prog))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_devices))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->device_list))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->options))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->callback))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->user_data))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_create_kern_t (XDR *xdrs, create_kern_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->prog))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->kernel_name, ~0))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->errorcode_ret))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->kernel))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_create_buf_t (XDR *xdrs, create_buf_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->context))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->flags))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->host_ptr.host_ptr_val, (u_int *) &objp->host_ptr.host_ptr_len, ~0))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->errorcode_ret))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->buffer))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_set_kern_arg_t (XDR *xdrs, set_kern_arg_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->kernel))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg_index))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->arg.arg_val, (u_int *) &objp->arg.arg_len, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_enq_ndr_kern_t (XDR *xdrs, enq_ndr_kern_t *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_quad_t (xdrs, &objp->command_queue))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->kernel))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->work_dim))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->global_work_offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->global_work_size))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->local_work_size))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->num_events_in_wait_list))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->work_dim);
		IXDR_PUT_LONG(buf, objp->global_work_offset);
		IXDR_PUT_LONG(buf, objp->global_work_size);
		IXDR_PUT_LONG(buf, objp->local_work_size);
		IXDR_PUT_LONG(buf, objp->num_events_in_wait_list);
		}
		 if (!xdr_quad_t (xdrs, &objp->event_wait_list))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->event))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->result))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_quad_t (xdrs, &objp->command_queue))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->kernel))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->work_dim))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->global_work_offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->global_work_size))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->local_work_size))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->num_events_in_wait_list))
				 return FALSE;

		} else {
		objp->work_dim = IXDR_GET_LONG(buf);
		objp->global_work_offset = IXDR_GET_LONG(buf);
		objp->global_work_size = IXDR_GET_LONG(buf);
		objp->local_work_size = IXDR_GET_LONG(buf);
		objp->num_events_in_wait_list = IXDR_GET_LONG(buf);
		}
		 if (!xdr_quad_t (xdrs, &objp->event_wait_list))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->event))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->result))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_quad_t (xdrs, &objp->command_queue))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->kernel))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->work_dim))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->global_work_offset))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->global_work_size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->local_work_size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_events_in_wait_list))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->event_wait_list))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->event))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_enq_read_buf_t (XDR *xdrs, enq_read_buf_t *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_quad_t (xdrs, &objp->command_queue))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->buffer))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->blocking_read))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cb))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->blocking_read);
		IXDR_PUT_LONG(buf, objp->offset);
		IXDR_PUT_LONG(buf, objp->cb);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->ptr.ptr_val, (u_int *) &objp->ptr.ptr_len, ~0))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->num_events_in_wait_list))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->event_wait_list))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->event))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->result))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_quad_t (xdrs, &objp->command_queue))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->buffer))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->blocking_read))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cb))
				 return FALSE;

		} else {
		objp->blocking_read = IXDR_GET_LONG(buf);
		objp->offset = IXDR_GET_LONG(buf);
		objp->cb = IXDR_GET_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->ptr.ptr_val, (u_int *) &objp->ptr.ptr_len, ~0))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->num_events_in_wait_list))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->event_wait_list))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->event))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->result))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_quad_t (xdrs, &objp->command_queue))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->buffer))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->blocking_read))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cb))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->ptr.ptr_val, (u_int *) &objp->ptr.ptr_len, ~0))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->num_events_in_wait_list))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->event_wait_list))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->event))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_enq_write_buf_t (XDR *xdrs, enq_write_buf_t *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_quad_t (xdrs, &objp->command_queue))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->buffer))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->blocking_write))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cb))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->blocking_write);
		IXDR_PUT_LONG(buf, objp->offset);
		IXDR_PUT_LONG(buf, objp->cb);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->ptr.ptr_val, (u_int *) &objp->ptr.ptr_len, ~0))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->num_events_in_wait_list))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->event_wait_list))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->event))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->result))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_quad_t (xdrs, &objp->command_queue))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->buffer))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->blocking_write))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cb))
				 return FALSE;

		} else {
		objp->blocking_write = IXDR_GET_LONG(buf);
		objp->offset = IXDR_GET_LONG(buf);
		objp->cb = IXDR_GET_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->ptr.ptr_val, (u_int *) &objp->ptr.ptr_len, ~0))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->num_events_in_wait_list))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->event_wait_list))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->event))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->result))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_quad_t (xdrs, &objp->command_queue))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->buffer))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->blocking_write))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cb))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->ptr.ptr_val, (u_int *) &objp->ptr.ptr_len, ~0))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->num_events_in_wait_list))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->event_wait_list))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->event))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_finish_t (XDR *xdrs, finish_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->command_queue))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_enq_map_buf_t (XDR *xdrs, enq_map_buf_t *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_quad_t (xdrs, &objp->command_queue))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->buffer))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->blocking_map))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->map_flags))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cb))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->num_events_in_wait_list))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->blocking_map);
		IXDR_PUT_LONG(buf, objp->map_flags);
		IXDR_PUT_LONG(buf, objp->offset);
		IXDR_PUT_LONG(buf, objp->cb);
		IXDR_PUT_LONG(buf, objp->num_events_in_wait_list);
		}
		 if (!xdr_quad_t (xdrs, &objp->event_wait_list))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->event))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->errorcode_ret))
			 return FALSE;
		 if (!xdr_bytes (xdrs, (char **)&objp->buf.buf_val, (u_int *) &objp->buf.buf_len, ~0))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_quad_t (xdrs, &objp->command_queue))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->buffer))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->blocking_map))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->map_flags))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cb))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->num_events_in_wait_list))
				 return FALSE;

		} else {
		objp->blocking_map = IXDR_GET_LONG(buf);
		objp->map_flags = IXDR_GET_LONG(buf);
		objp->offset = IXDR_GET_LONG(buf);
		objp->cb = IXDR_GET_LONG(buf);
		objp->num_events_in_wait_list = IXDR_GET_LONG(buf);
		}
		 if (!xdr_quad_t (xdrs, &objp->event_wait_list))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->event))
			 return FALSE;
		 if (!xdr_quad_t (xdrs, &objp->errorcode_ret))
			 return FALSE;
		 if (!xdr_bytes (xdrs, (char **)&objp->buf.buf_val, (u_int *) &objp->buf.buf_len, ~0))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_quad_t (xdrs, &objp->command_queue))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->buffer))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->blocking_map))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->map_flags))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cb))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_events_in_wait_list))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->event_wait_list))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->event))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->errorcode_ret))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->buf.buf_val, (u_int *) &objp->buf.buf_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_release_mem_t (XDR *xdrs, release_mem_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->buffer))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_release_prog_t (XDR *xdrs, release_prog_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->prog))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_release_kern_t (XDR *xdrs, release_kern_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->kernel))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_release_cqueue_t (XDR *xdrs, release_cqueue_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->command_queue))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_release_ctx_t (XDR *xdrs, release_ctx_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->context))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}
